#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 7
#define MS_VERSION_MINOR 0
#define MS_VERSION_REV 2
#define MS_VERSION "7.0.2"
#define MS_VERSION_NUM  70002 

#endif

